### ISSUE TITLE
KeyError: 'CRYPTOCOMPARE_API_KEY'

### ISSUE THREAD

**Issue by kopdaniil** [systamental/cryptodatapy#12]
'''
from cryptodatapy.extract.datarequest import DataRequest
from cryptodatapy.extract.getdata import GetData
data_req = DataRequest(
  source='coinmetrics',           
  tickers=['btc', 'eth'], 
  fields=['close', 'add_act', 'hashrate'], 
  req='d',
  start_date='2016-01-01')

GetData(data_req).get_series()
'''

'''
    cryptocompare_api_key: str = os.environ['CRYPTOCOMPARE_API_KEY']
                                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'CRYPTOCOMPARE_API_KEY'
'''

**Comment by nicklatin** [comment]
Sorry for not responding earlier to this. Yes, you need to add your cryptocompare API key to your environment variables as 'CRYPTOCOMPARE_API_KEY'. This should take care of it.
