### ISSUE TITLE
pytest should not require API keys

### ISSUE THREAD

**Issue by closedLoop** [systamental/cryptodatapy#3]
running `python -m pytest` yields three errors related to pulling in data from various APIs

```
======================== short test summary info ========================
ERROR tests/test_filter.py - TypeError: Set your api key. Alternativel...
ERROR tests/test_impute.py - TypeError: Set your api key. Alternativel...
ERROR tests/test_od.py - TypeError: Set your api key. Alternatively, y...
!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!
```

In general unit tests shouldn't rely on external services.  It would be better if we saved down some example data as a CSV that is stored in the repo.

**Comment by nicklatin** [comment]
Added data dir to tests to address this issue.
